export { default as icon } from "./icon.png";
export { default as slide1 } from "./slide1.png";
export { default as slide2 } from "./slide2.png";
export { default as slide3 } from "./slide3.png";
export { default as milkCF } from "./milkCF.png";
export { default as darkCF } from "./darkCF.png";
export { default as about } from "./about.png";
export { default as branch1 } from "./branch1.jpg";
export { default as branch2 } from "./branch2.jpg";
